[build]
  publish = "."
  command = "echo 'Static site build complete'"

[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"